### ISSUE TITLE
cp: '/usr/lib/locale' e '/usr/lib.new/locale' are the same file

### ISSUE THREAD

**Issue by lraschi-linkengineering** [mgorny/unsymlink-lib#14] opened 2021-04-21 07:11 UTC
Hello,

I have to migrate my amd 17.0 profile to 17.1 new profile on my gentoo.
Unfortunately your tool fails.
After selecting the --migrate option, the tool reports
"cp: '/usr/lib/locale' e '/usr/lib.new/locale' are the same file"
It sounds strange because the /usr/lib.new is created by your tool.
I posted a support request on gentoo forum, https://forums.gentoo.org/viewtopic-t-1133943.html .
There you'll find the output of --analyze, --pretend and --migrate parameter.
Thank you,

Lorenzo

**Comment by thesamesam** [comment] 2022-12-20 08:54
Closing as https://forums.gentoo.org/viewtopic-t-1133943.html has a resolution for this, not a bug in the tool.

**Closed as not planned** 2022-12-20 08:54 UTC
